# Generated by Django 6.0.2 on 2026-03-09 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='existencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 11 dígitos numéricos, sin guiones.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cedula_rnc',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El RNC/Cédula debe tener 9 u 11 dígitos numéricos, sin guiones.', regex='^(\\d{9}|\\d{11})$')]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
