# Generated by Django 6.0.2 on 2026-03-31 20:47

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_articulo_existencia_alter_empleado_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=11, unique=True, validators=[gestion.models.validar_cedula_dominicana]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cedula_rnc',
            field=models.CharField(max_length=11, unique=True, validators=[gestion.models.validar_rnc_dominicano]),
        ),
    ]
